import { Button } from "./ui/button";
import { Printer, X } from "lucide-react";

export type ReceiptPayment = {
  receiptNumber: string;
  amount: string | number;
  paymentMethod: string;
  paymentDate: string;
  referenceNumber?: string | null;
  notes?: string | null;
};

type Props = {
  open: boolean;
  onClose: () => void;
  schoolName: string;
  studentName: string;
  admissionNumber?: string;
  payments: ReceiptPayment[];
  outstandingAfter?: number | null;
};

const METHOD_LABELS: Record<string, string> = {
  mtnMomo: "MTN MoMo",
  airtelMoney: "Airtel Money",
  cash: "Cash",
  bankTransfer: "Bank transfer",
};

export function PaymentReceipt({
  open,
  onClose,
  schoolName,
  studentName,
  admissionNumber,
  payments,
  outstandingAfter,
}: Props) {
  if (!open || payments.length === 0) return null;

  const total = payments.reduce((s, p) => s + Number(p.amount), 0);

  function handlePrint() {
    window.print();
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4 print:static print:bg-white print:p-0">
      <div className="bg-card rounded-xl shadow-xl max-w-md w-full max-h-[90vh] overflow-y-auto print:shadow-none print:max-w-none print:rounded-none">
        <div className="flex items-center justify-between p-4 border-b print:hidden">
          <h2 className="font-semibold text-foreground">Payment receipt</h2>
          <div className="flex gap-2">
            <Button size="sm" onClick={handlePrint} className="bg-indigo-600 hover:bg-indigo-700">
              <Printer className="h-4 w-4 mr-1" /> Print
            </Button>
            <Button size="sm" variant="outline" onClick={onClose}>
              <X className="h-4 w-4" />
            </Button>
          </div>
        </div>

        <div className="p-6 space-y-4 text-sm" id="scholarbase-receipt">
          <div className="text-center border-b pb-4">
            <p className="text-lg font-bold text-foreground">{schoolName}</p>
            <p className="text-xs text-muted-foreground mt-1">Fee payment receipt</p>
          </div>

          <div className="space-y-1">
            <Row label="Student" value={studentName} />
            {admissionNumber && <Row label="Admission no." value={admissionNumber} />}
            <Row label="Date" value={payments[0]?.paymentDate ?? "—"} />
            <Row
              label="Method"
              value={METHOD_LABELS[payments[0]?.paymentMethod] ?? payments[0]?.paymentMethod ?? "—"}
            />
            {payments[0]?.referenceNumber && (
              <Row label="Reference" value={payments[0].referenceNumber} />
            )}
          </div>

          <div className="border rounded-lg overflow-hidden">
            <table className="w-full text-sm">
              <thead className="bg-muted">
                <tr>
                  <th className="text-left px-3 py-2 font-medium text-muted-foreground">Receipt #</th>
                  <th className="text-right px-3 py-2 font-medium text-muted-foreground">Amount</th>
                </tr>
              </thead>
              <tbody>
                {payments.map((p) => (
                  <tr key={p.receiptNumber} className="border-t">
                    <td className="px-3 py-2 font-mono text-xs">{p.receiptNumber}</td>
                    <td className="px-3 py-2 text-right">{Number(p.amount).toLocaleString()} UGX</td>
                  </tr>
                ))}
              </tbody>
              <tfoot>
                <tr className="border-t bg-muted font-semibold">
                  <td className="px-3 py-2">Total</td>
                  <td className="px-3 py-2 text-right">{total.toLocaleString()} UGX</td>
                </tr>
              </tfoot>
            </table>
          </div>

          {outstandingAfter != null && (
            <p className="text-center text-xs text-muted-foreground">
              Outstanding balance after this payment:{" "}
              <span className="font-medium text-foreground">
                {Math.round(outstandingAfter).toLocaleString()} UGX
              </span>
            </p>
          )}

          <p className="text-center text-[10px] text-gray-400 pt-2">
            Generated by ScholarBase · Keep this receipt for your records
          </p>
        </div>
      </div>
    </div>
  );
}

function Row({ label, value }: { label: string; value: string }) {
  return (
    <div className="flex justify-between gap-4">
      <span className="text-muted-foreground">{label}</span>
      <span className="font-medium text-foreground text-right">{value}</span>
    </div>
  );
}
